package Telas;

import BD.DAO.EnderecoDAO;
import BD.DAO.FuncionarioDAO;
import BD.DAO.UsuarioDAO;
import DadosGlobaisTemporarios.Logado;
import Entidades.Endereco;
import Entidades.Funcionario;
import Entidades.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leo
 */
public class TelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdm
     */
    public TelaAdm() {
        initComponents();
        this.setLocationRelativeTo(null);
        Funcionario f = new Funcionario();
        f.setMatricula();
        numMatricula.setText(Integer.toString(f.getMatricula()));
        painelTipoDoutor.setVisible(false);
        readFullFuncionario();
        
//        nomeUnidade.setText(Logado.getUpa().getId()+" - "+Logado.getUpa().getNome());
//        nomeUser.setText(Logado.getFuncionario().getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JPanel();
        infosLogin = new javax.swing.JPanel();
        nomeUnidade = new javax.swing.JLabel();
        nomeUser = new javax.swing.JLabel();
        menus = new javax.swing.JTabbedPane();
        painelFuncionarios = new javax.swing.JPanel();
        obrigatorio = new javax.swing.JTabbedPane();
        cadastroFunc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeFunc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        numMatricula = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipoCadastro = new javax.swing.JComboBox<>();
        documentolbl1 = new javax.swing.JLabel();
        cep = new javax.swing.JFormattedTextField();
        documentolbl2 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        documentolbl3 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        cadastrarFunc = new javax.swing.JButton();
        painelTipoDoutor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        documentolbl = new javax.swing.JLabel();
        especializacao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        documentolbl4 = new javax.swing.JLabel();
        complemento = new javax.swing.JTextField();
        documentolbl5 = new javax.swing.JLabel();
        numLogra = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        uf = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbFunc = new javax.swing.JTable();
        painelUsuarios = new javax.swing.JPanel();
        menuFunc1 = new javax.swing.JTabbedPane();
        cadastroUser = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nomeUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        confirmaSenha = new javax.swing.JPasswordField();
        senha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        btnCadastraUser = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        lblCadastroVinculado = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbFuncUser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainFrame.setBackground(new java.awt.Color(51, 153, 0));

        infosLogin.setBackground(new java.awt.Color(255, 255, 255));

        nomeUnidade.setBackground(new java.awt.Color(255, 255, 255));
        nomeUnidade.setText("Nome Unidade");
        nomeUnidade.setOpaque(true);

        nomeUser.setBackground(new java.awt.Color(255, 255, 255));
        nomeUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeUser.setText("Nome Usuario");
        nomeUser.setOpaque(true);

        javax.swing.GroupLayout infosLoginLayout = new javax.swing.GroupLayout(infosLogin);
        infosLogin.setLayout(infosLoginLayout);
        infosLoginLayout.setHorizontalGroup(
            infosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infosLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeUser, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );
        infosLoginLayout.setVerticalGroup(
            infosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomeUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nomeUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menus.setBackground(new java.awt.Color(255, 255, 255));

        painelFuncionarios.setBackground(new java.awt.Color(255, 255, 255));

        obrigatorio.setName(""); // NOI18N
        obrigatorio.setOpaque(true);

        jLabel1.setText("Nome: ");

        jLabel2.setText("CPF:");

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Matricula:");

        numMatricula.setText("lalalalalala");

        jLabel4.setText("Tipo:");

        tipoCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A - Administrativo", "D - Dentista", "M - Médico", "R - Recepcionista" }));
        tipoCadastro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoCadastroItemStateChanged(evt);
            }
        });
        tipoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCadastroActionPerformed(evt);
            }
        });

        documentolbl1.setText("CEP:");

        try {
            cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepActionPerformed(evt);
            }
        });

        documentolbl2.setText("Endereço:");

        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });

        documentolbl3.setText("Bairro:");

        cadastrarFunc.setText("Cadastrar");
        cadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncActionPerformed(evt);
            }
        });

        jLabel5.setText("Especialidade:");

        documentolbl.setText("Documento:");

        especializacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especializacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTipoDoutorLayout = new javax.swing.GroupLayout(painelTipoDoutor);
        painelTipoDoutor.setLayout(painelTipoDoutorLayout);
        painelTipoDoutorLayout.setHorizontalGroup(
            painelTipoDoutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTipoDoutorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(documentolbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(especializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        painelTipoDoutorLayout.setVerticalGroup(
            painelTipoDoutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTipoDoutorLayout.createSequentialGroup()
                .addGroup(painelTipoDoutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentolbl)
                    .addComponent(especializacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel11.setText("Telefone:");

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        documentolbl4.setText("Complemento:");

        complemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complementoActionPerformed(evt);
            }
        });

        documentolbl5.setText("Numero:");

        numLogra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numLograActionPerformed(evt);
            }
        });

        jLabel12.setText("UF:");

        uf.setText("PR");

        javax.swing.GroupLayout cadastroFuncLayout = new javax.swing.GroupLayout(cadastroFunc);
        cadastroFunc.setLayout(cadastroFuncLayout);
        cadastroFuncLayout.setHorizontalGroup(
            cadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroFuncLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(cadastrarFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(219, 219, 219))
                    .addGroup(cadastroFuncLayout.createSequentialGroup()
                        .addGroup(cadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroFuncLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(nomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadastroFuncLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numMatricula)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tipoCadastro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80))
                    .addGroup(cadastroFuncLayout.createSequentialGroup()
                        .addGroup(cadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroFuncLayout.createSequentialGroup()
                                .addComponent(documentolbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadastroFuncLayout.createSequentialGroup()
                                .addComponent(documentolbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(documentolbl4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(documentolbl5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numLogra, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(documentolbl3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(painelTipoDoutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cadastroFuncLayout.setVerticalGroup(
            cadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numMatricula))
                .addGap(40, 40, 40)
                .addGroup(cadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tipoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(painelTipoDoutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentolbl2)
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentolbl4)
                    .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentolbl5)
                    .addComponent(numLogra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentolbl3)
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(documentolbl1)
                        .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(cadastrarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        obrigatorio.addTab("Cadastro", cadastroFunc);

        tbFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "MATRICULA", "TIPO", "NOME", "ESPECIALIZAÇÃO", "TELEFONE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbFunc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        obrigatorio.addTab("Lista", jPanel2);

        javax.swing.GroupLayout painelFuncionariosLayout = new javax.swing.GroupLayout(painelFuncionarios);
        painelFuncionarios.setLayout(painelFuncionariosLayout);
        painelFuncionariosLayout.setHorizontalGroup(
            painelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(obrigatorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        painelFuncionariosLayout.setVerticalGroup(
            painelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(obrigatorio)
        );

        menus.addTab("Funcionarios", painelFuncionarios);

        menuFunc1.setOpaque(true);

        jLabel6.setText("Nome de Usuario:");

        nomeUsuario.setText("nome.sobrenome");

        jLabel8.setText("Senha: ");

        jLabel9.setText("Confirmar senha:");

        confirmaSenha.setText("jPasswordField1");

        senha.setText("jPasswordField2");

        jLabel7.setText("Email: ");

        email.setText("exemplo@generico.com");

        btnCadastraUser.setText("Concluir Cadastro");
        btnCadastraUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraUserActionPerformed(evt);
            }
        });

        jLabel10.setText("Cadastro Vinculado: ");

        tbFuncUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "MATRICULA", "NOME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tbFuncUser);

        javax.swing.GroupLayout cadastroUserLayout = new javax.swing.GroupLayout(cadastroUser);
        cadastroUser.setLayout(cadastroUserLayout);
        cadastroUserLayout.setHorizontalGroup(
            cadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroUserLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cadastroUserLayout.createSequentialGroup()
                        .addComponent(btnCadastraUser, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(cadastroUserLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(lblCadastroVinculado, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(cadastroUserLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(senha))
                        .addGroup(cadastroUserLayout.createSequentialGroup()
                            .addGroup(cadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(cadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nomeUsuario)
                                .addComponent(confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(cadastroUserLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
        );
        cadastroUserLayout.setVerticalGroup(
            cadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroUserLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(cadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblCadastroVinculado))
                .addGap(46, 46, 46)
                .addGroup(cadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(cadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(cadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(cadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastraUser)
                .addGap(26, 26, 26))
            .addGroup(cadastroUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        menuFunc1.addTab("Cadastro", cadastroUser);

        javax.swing.GroupLayout painelUsuariosLayout = new javax.swing.GroupLayout(painelUsuarios);
        painelUsuarios.setLayout(painelUsuariosLayout);
        painelUsuariosLayout.setHorizontalGroup(
            painelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuFunc1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        painelUsuariosLayout.setVerticalGroup(
            painelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuFunc1)
        );

        menus.addTab("Usuarios", painelUsuarios);

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infosLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainFrameLayout.createSequentialGroup()
                .addComponent(infosLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraUserActionPerformed
        UsuarioDAO udao = new UsuarioDAO();
        Usuario u = new Usuario();
        String s = new String(senha.getPassword()); //casta o passfield char pra string
        String sc = new String(confirmaSenha.getPassword());
        Funcionario f = new Funcionario();

        if(udao.confereLogin(nomeUsuario.getText())){
            JOptionPane.showMessageDialog(null, "Nome de Usuario: " +nomeUsuario.getText()+ " já esta sendo utilizado!");
        }else{
            if(!(s.equals(sc))){
                JOptionPane.showMessageDialog(null, "Os campos SENHA e CONFIRMA SENHA são diferentes!");
            }else{
                f.setId((int) tbFuncUser.getValueAt(tbFuncUser.getSelectedRow(), 0));
                u.setEmail(email.getText());
                u.setLogin(nomeUsuario.getText());
                u.setSenha(s);
                u.setPessoa(f);

                udao.salvarUsuario(u);
                limpaCampoUsuarios();
            }
        }
    }//GEN-LAST:event_btnCadastraUserActionPerformed

    private void numLograActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numLograActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numLograActionPerformed

    private void complementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complementoActionPerformed

    private void especializacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especializacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especializacaoActionPerformed

    private void cadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncActionPerformed
        Endereco e = new Endereco();
        Funcionario f = new Funcionario();
        e.setBairro(bairro.getText());
        e.setCep(cep.getText());
        e.setEndereco(endereco.getText());
        e.setComplemento(complemento.getText());
        e.setNumero(Integer.parseInt(numLogra.getText()));
        e.setUF(uf.getText());

        f.setEndereco(e);
        f.setCpf(cpf.getText());
        f.setTipo(tipoCadastro.getSelectedItem().toString().substring(0, 1));//pega o primeiro caractere
        f.setTelefone(telefone.getText());
        f.setNome(nomeFunc.getText());

        int doc = "".equals(documento.getText())? 0 : Integer.parseInt(documento.getText());
        f.setDocumento(doc);
        f.setMatricula(Integer.parseInt(numMatricula.getText()));
        f.setExp(especializacao.getText());

        FuncionarioDAO salvar = new FuncionarioDAO();
        EnderecoDAO salvar2 = new EnderecoDAO();
        salvar2.salvarCep(e);
        salvar.salvarCadastro(f);

        limparCamposTelaCadastro();
        numMatricula.setText(Integer.toString(f.getMatricula()));
        readFullFuncionario();
    }//GEN-LAST:event_cadastrarFuncActionPerformed

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoActionPerformed

    private void cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepActionPerformed

    private void tipoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCadastroActionPerformed
        boolean verifica = tipoCadastro.getSelectedItem().equals("M - Médico");
        verifica = verifica || tipoCadastro.getSelectedItem().equals("D - Dentista");
        painelTipoDoutor.setVisible(verifica);
    }//GEN-LAST:event_tipoCadastroActionPerformed

    private void tipoCadastroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoCadastroItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCadastroItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdm().setVisible(true);
            }
        });
    }
    public void readFullFuncionario(){
        DefaultTableModel listaF = (DefaultTableModel) tbFunc.getModel();
        DefaultTableModel listaFUser = (DefaultTableModel) tbFuncUser.getModel();
        listaF.setNumRows(0);
        listaFUser.setNumRows(0);
        
        FuncionarioDAO fdao = new FuncionarioDAO();
        
        for(Funcionario f : fdao.lerListaFuncionario()){
            listaF.addRow(new Object[]{
                f.getMatricula(),
                f.getTipo(),
                f.getNome(),
                f.getExp(),
                f.getTelefone()
            });
            listaFUser.addRow(new Object[]{
                f.getId(),
                f.getMatricula(),
                f.getNome()
            });
        }
    }
  

    public void limparCamposTelaCadastro(){
        bairro.setText("");
        cep.setText("");
        endereco.setText("");
        complemento.setText("");
        numLogra.setText("");
        uf.setText("");
        
        cpf.setText("");
        telefone.setText("");
        nomeFunc.setText("");
        
        documento.setText("");
        numMatricula.setText("");
        especializacao.setText("");
    }
    
    public void limpaCampoUsuarios(){
        email.setText("");
        nomeUsuario.setText("");
        senha.setText("");
        confirmaSenha.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro;
    private javax.swing.JToggleButton btnCadastraUser;
    private javax.swing.JButton cadastrarFunc;
    private javax.swing.JPanel cadastroFunc;
    private javax.swing.JPanel cadastroUser;
    private javax.swing.JFormattedTextField cep;
    private javax.swing.JTextField complemento;
    private javax.swing.JPasswordField confirmaSenha;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JTextField documento;
    private javax.swing.JLabel documentolbl;
    private javax.swing.JLabel documentolbl1;
    private javax.swing.JLabel documentolbl2;
    private javax.swing.JLabel documentolbl3;
    private javax.swing.JLabel documentolbl4;
    private javax.swing.JLabel documentolbl5;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField especializacao;
    private javax.swing.JPanel infosLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblCadastroVinculado;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JTabbedPane menuFunc1;
    private javax.swing.JTabbedPane menus;
    private javax.swing.JTextField nomeFunc;
    private javax.swing.JLabel nomeUnidade;
    private javax.swing.JLabel nomeUser;
    private javax.swing.JTextField nomeUsuario;
    private javax.swing.JTextField numLogra;
    private javax.swing.JLabel numMatricula;
    private javax.swing.JTabbedPane obrigatorio;
    private javax.swing.JPanel painelFuncionarios;
    private javax.swing.JPanel painelTipoDoutor;
    private javax.swing.JPanel painelUsuarios;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTable tbFunc;
    private javax.swing.JTable tbFuncUser;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JComboBox<String> tipoCadastro;
    private javax.swing.JTextField uf;
    // End of variables declaration//GEN-END:variables
}
